-- Preserve all original rows; retain the original status_runs API through a view.
-- Reload the REST schema only after the migration transaction commits.
notify pgrst, 'reload schema';
-- The platform's DDL event trigger runs as its owner and needs no API grants.
-- Keep its automatic RLS protection while closing the pre-existing advisor warning.
do $$
begin
  if exists (select 1 from pg_proc where oid = to_regprocedure('public.rls_auto_enable()') and prorettype = 'event_trigger'::regtype) then
    revoke execute on function public.rls_auto_enable() from public, anon, authenticated;
  end if;
end;
$$;
create table public.status_collector_leases (
  runner text primary key,
  enabled boolean not null default false,
  capacity_limit_bytes bigint not null default 400000000 check (capacity_limit_bytes between 1000000 and 400000000),
  targets jsonb not null check (jsonb_typeof(targets) = 'array' and jsonb_array_length(targets) between 1 and 24 and octet_length(targets::text) <= 100000),
  lease_token uuid,
  lease_slot timestamptz,
  lease_targets jsonb,
  leased_at timestamptz,
  lease_expires_at timestamptz,
  committed_slot timestamptz
);

create table public.status_target_configs (
  hash bytea primary key,
  targets jsonb not null,
  check (hash = sha256(convert_to(targets::text, 'UTF8'))),
  check (jsonb_typeof(targets) = 'array' and jsonb_array_length(targets) between 1 and 24 and octet_length(targets::text) <= 100000)
);

create table public.status_probe_batches (
  runner text not null,
  slot timestamptz not null,
  token uuid not null unique,
  first_checked_at timestamptz not null,
  last_checked_at timestamptz not null,
  target_config_hash bytea not null references public.status_target_configs(hash),
  records jsonb not null check (jsonb_typeof(records) = 'array' and jsonb_array_length(records) between 1 and 24),
  created_at timestamptz not null default now(),
  primary key (runner, slot),
  check (last_checked_at >= first_checked_at and last_checked_at - first_checked_at <= interval '120 seconds')
);
create index status_probe_batches_window_idx on public.status_probe_batches (runner, first_checked_at);

create table public.status_current (
  runner text primary key,
  id bigint not null unique default nextval('public.status_runs_id_seq'::regclass),
  generated_at timestamptz not null,
  summary jsonb not null,
  created_at timestamptz not null default now()
);
alter table public.status_collector_leases enable row level security;
alter table public.status_target_configs enable row level security;
alter table public.status_probe_batches enable row level security;
alter table public.status_current enable row level security;
revoke all on public.status_collector_leases, public.status_target_configs, public.status_probe_batches, public.status_current from anon, authenticated;
grant select, insert, update on public.status_collector_leases to service_role;
grant select, insert on public.status_target_configs to service_role;
grant select, insert on public.status_probe_batches to service_role;
grant select, insert, update on public.status_current to service_role;
grant usage, select on sequence public.status_runs_id_seq to service_role;
grant select on public.status_current to anon, authenticated;
create policy "public can read current status" on public.status_current for select to anon, authenticated using (true);

alter table public.status_runs rename to status_runs_legacy;
create view public.status_runs with (security_invoker = true) as
  select id, runner, generated_at, (summary->>'window_days')::integer as window_days,
    jsonb_array_length(summary->'targets') as target_count, summary, created_at from public.status_current
  union all
  select id, runner, generated_at, window_days, target_count, summary, created_at from public.status_runs_legacy;
grant select on public.status_runs to anon, authenticated;
grant select, insert on public.status_runs to service_role;
alter view public.status_runs alter column runner set default 'github-actions';
alter view public.status_runs alter column window_days set default 90;
alter view public.status_runs alter column created_at set default now();

-- Existing manual imports and an in-flight legacy job remain compatible during
-- cutover. New collection never appends a redundant historical snapshot.
create function public.insert_legacy_status_run()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if new.id is not null then raise exception 'Status run ID is generated by the database'; end if;
  insert into public.status_runs_legacy (runner, generated_at, window_days, target_count, summary, created_at)
    values (new.runner, new.generated_at, new.window_days, new.target_count, new.summary, new.created_at)
    returning id, runner, generated_at, window_days, target_count, summary, created_at into new;
  return new;
end;
$$;
revoke all on function public.insert_legacy_status_run() from public, anon, authenticated;
grant execute on function public.insert_legacy_status_run() to service_role;
create trigger status_runs_legacy_insert instead of insert on public.status_runs
  for each row execute function public.insert_legacy_status_run();

create view public.status_latest with (security_invoker = true) as
  select runner, generated_at, summary from public.status_runs;
grant select on public.status_latest to anon, authenticated, service_role;

-- Both representations remain readable. The bounded batch time span permits an
-- indexed overlap scan even when an observation crosses midnight.
create function public.status_raw_window(p_runner text, p_start timestamptz, p_end timestamptz)
returns table (checked_at timestamptz, target_id text, status integer, ms integer, error_class text)
language sql stable security invoker set search_path = '' as $$
  select s.checked_at, s.target_id, s.status, s.ms, s.error_class
  from public.status_samples s
  where s.runner = p_runner and s.checked_at >= p_start and s.checked_at < p_end
  union all
  select (r->>'t')::timestamptz, r->>'id', (r->>'s')::integer, (r->>'ms')::integer, r->>'e'
  from public.status_probe_batches b cross join lateral jsonb_array_elements(b.records) r
  where b.runner = p_runner
    and b.first_checked_at >= p_start - interval '120 seconds'
    and b.first_checked_at < p_end and b.last_checked_at >= p_start
    and (r->>'t')::timestamptz >= p_start and (r->>'t')::timestamptz < p_end;
$$;
revoke all on function public.status_raw_window(text, timestamptz, timestamptz) from public, anon, authenticated;
grant execute on function public.status_raw_window(text, timestamptz, timestamptz) to service_role;

create function public.claim_status_collection(p_runner text)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  v_state public.status_collector_leases%rowtype;
  v_now timestamptz;
  v_slot timestamptz;
  v_token uuid;
begin
  select * into v_state from public.status_collector_leases where runner = p_runner for update skip locked;
  if not found then
    return jsonb_build_object('state', case when exists (select 1 from public.status_collector_leases where runner = p_runner) then 'busy' else 'disabled' end);
  end if;
  if not v_state.enabled then return jsonb_build_object('state', 'disabled'); end if;
  if pg_database_size(current_database()) >= v_state.capacity_limit_bytes then
    return jsonb_build_object('state', 'capacity');
  end if;
  v_now := clock_timestamp();
  v_slot := date_bin(interval '5 minutes', v_now, timestamptz '1970-01-01 00:00:00+00');
  if v_state.committed_slot >= v_slot then return jsonb_build_object('state', 'complete'); end if;
  if v_state.lease_expires_at > v_now then return jsonb_build_object('state', 'busy'); end if;
  v_token := gen_random_uuid();
  update public.status_collector_leases set lease_token = v_token, lease_slot = v_slot, lease_targets = v_state.targets,
    leased_at = v_now, lease_expires_at = v_now + interval '145 seconds' where runner = p_runner;
  return jsonb_build_object('state', 'claimed', 'token', v_token, 'slot', v_slot,
    'started_at', v_now, 'targets', v_state.targets);
end;
$$;
revoke all on function public.claim_status_collection(text) from public, anon, authenticated;
grant execute on function public.claim_status_collection(text) to service_role;

create function public.commit_status_collection(p_runner text, p_token uuid, p_records jsonb)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  v_state public.status_collector_leases%rowtype;
  v_existing public.status_probe_batches%rowtype;
  v_now timestamptz;
  v_first timestamptz;
  v_last timestamptz;
  v_summary jsonb;
  v_config_hash bytea;
begin
  select * into v_state from public.status_collector_leases where runner = p_runner for update;
  if not found then raise exception 'Collector runner is not configured'; end if;
  select * into v_existing from public.status_probe_batches where runner = p_runner and token = p_token;
  if found then
    if v_existing.records is distinct from p_records then raise exception 'Committed batch differs from retry'; end if;
    return jsonb_build_object('state', 'complete', 'slot', v_existing.slot);
  end if;
  v_now := clock_timestamp();
  if not v_state.enabled or v_state.lease_token is distinct from p_token or v_state.lease_expires_at <= v_now
    or v_state.lease_expires_at is null then raise exception 'Collector lease is unavailable'; end if;
  if jsonb_typeof(p_records) is distinct from 'array' then raise exception 'Collector records must be an array'; end if;
  if jsonb_array_length(p_records) <> jsonb_array_length(v_state.lease_targets) or octet_length(p_records::text) > 131072
    then raise exception 'Collector batch has invalid size'; end if;
  if (select count(distinct r->>'id') from jsonb_array_elements(p_records) r) <> jsonb_array_length(p_records)
    then raise exception 'Collector target IDs must be unique'; end if;
  if exists (select 1 from jsonb_array_elements(p_records) r where
      jsonb_typeof(r) is distinct from 'object' or not (r ?& array['t','id','s','ms'])
      or jsonb_typeof(r->'t') is distinct from 'string' or jsonb_typeof(r->'id') is distinct from 'string'
      or jsonb_typeof(r->'ms') is distinct from 'number' or (r->>'ms') !~ '^[0-9]+$'
      or (r->>'ms')::numeric > 120000
      or (r->'s' <> 'null'::jsonb and (jsonb_typeof(r->'s') is distinct from 'number' or (r->>'s') !~ '^[0-9]+$' or (r->>'s')::numeric not between 100 and 599))
      or (r ? 'e' and (jsonb_typeof(r->'e') is distinct from 'string' or r->>'e' not in ('timeout','dns','tls','conn','abort')))
      or not exists (select 1 from jsonb_array_elements(v_state.lease_targets) t where t->>'id' = r->>'id'))
    then raise exception 'Collector record is invalid'; end if;
  select min((r->>'t')::timestamptz), max((r->>'t')::timestamptz) into v_first, v_last from jsonb_array_elements(p_records) r;
  if v_first < v_state.leased_at - interval '5 seconds' or v_last > v_now + interval '5 seconds' or v_last - v_first > interval '120 seconds'
    then raise exception 'Collector observation is outside its lease'; end if;
  v_config_hash := sha256(convert_to(v_state.lease_targets::text, 'UTF8'));
  insert into public.status_target_configs (hash, targets) values (v_config_hash, v_state.lease_targets) on conflict (hash) do nothing;
  if (select targets from public.status_target_configs where hash = v_config_hash) is distinct from v_state.lease_targets
    then raise exception 'Collector configuration hash conflict'; end if;
  insert into public.status_probe_batches (runner, slot, token, first_checked_at, last_checked_at, target_config_hash, records)
    values (p_runner, v_state.lease_slot, p_token, v_first, v_last, v_config_hash, p_records);
  v_now := greatest(v_now, v_last, coalesce((select generated_at from public.status_current where runner = p_runner), '-infinity'::timestamptz));
  v_summary := public.build_status_projection(p_runner, v_now, v_state.lease_targets, false);
  insert into public.status_current (runner, generated_at, summary) values (p_runner, v_now, v_summary)
    on conflict (runner) do update set generated_at = excluded.generated_at, summary = excluded.summary;
  update public.status_collector_leases set committed_slot = v_state.lease_slot, lease_expires_at = null where runner = p_runner;
  return jsonb_build_object('state', 'complete', 'slot', v_state.lease_slot);
end;
$$;
revoke all on function public.commit_status_collection(text, uuid, jsonb) from public, anon, authenticated;
grant execute on function public.commit_status_collection(text, uuid, jsonb) to service_role;

-- Incremental runs recompute the affected UTC days, including midnight overlap.
-- The daily full rebuild recalculates rolling percentiles from original samples.
create function public.build_status_projection(p_runner text, p_now timestamptz, p_targets jsonb, p_full boolean)
returns jsonb language sql stable security invoker set search_path = '' as $$
with bounds as (
  select (p_now at time zone 'UTC')::date as today,
    (p_now at time zone 'UTC')::date - 89 as oldest,
    case when p_full then (p_now at time zone 'UTC')::date - 89
      else ((p_now - interval '150 seconds') at time zone 'UTC')::date end as first_day
), previous as (
  select summary from public.status_latest where runner = p_runner and generated_at <= p_now
    order by generated_at desc limit 1
), targets as (
  select t, ord, t->>'id' as id, (t->>'expect')::integer as expect,
    (select old from previous, jsonb_array_elements(summary->'targets') old where old->>'id' = t->>'id' limit 1) as old
  from jsonb_array_elements(p_targets) with ordinality config(t, ord)
), records as materialized (
  select r.* from bounds b cross join lateral public.status_raw_window(p_runner,
    b.first_day::timestamp at time zone 'UTC', (b.today + 1)::timestamp at time zone 'UTC') r
), fresh_days as (
  select r.target_id as id, (r.checked_at at time zone 'UTC')::date as d,
    count(*) as n, count(*) filter (where r.status = t.expect and r.error_class is null) as ok,
    percentile_disc(0.5) within group (order by r.ms) as p50
  from records r join targets t on t.id = r.target_id group by r.target_id, (r.checked_at at time zone 'UTC')::date
), days as (
  select id, d, n, ok, p50 from fresh_days
  union all
  select t.id, (d->>'d')::date, (d->>'n')::bigint, (d->>'ok')::bigint, (d->>'p50')::integer
  from targets t cross join bounds b cross join lateral jsonb_array_elements(coalesce(t.old->'days', '[]'::jsonb)) d
  where not p_full and (d->>'d')::date >= b.oldest and (d->>'d')::date < b.first_day
), day_lists as (
  select id, jsonb_agg(jsonb_build_object('d', d::text, 'n', n, 'ok', ok, 'p50', p50) order by d) as days,
    sum(n) as total, sum(ok) as ok, bool_or(d < (select first_day from bounds)) as has_old_days
  from days group by id
), ok_percentiles as (
  select t.id, percentile_disc(0.5) within group (order by r.ms) as p50,
    percentile_disc(0.95) within group (order by r.ms) as p95
  from targets t join records r on r.target_id = t.id and r.status = t.expect and r.error_class is null group by t.id
), weighted as (
  select id, p50, sum(n) over (partition by id order by p50 rows unbounded preceding) as cumulative,
    sum(n) over (partition by id) as total from days where p50 is not null
), fallback as (
  select id, min(p50) as p50 from weighted where cumulative >= ceil(total * 0.5) group by id
), latest as (
  select distinct on (target_id) target_id as id, checked_at, status, ms, error_class
    from records order by target_id, checked_at desc
), result as (
  select t.ord, jsonb_build_object(
    'id', t.id, 'name', t.t->>'name', 'url', t.t->>'url',
    'current', case when l.checked_at is not null then
      jsonb_build_object('state', case when l.status = t.expect and l.error_class is null then 'up' else 'down' end,
        'status', l.status, 'ms', l.ms, 'checked_at', to_char(l.checked_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
        || case when l.error_class is null then '{}'::jsonb else jsonb_build_object('error_class', l.error_class) end
      when not p_full and (t.old->'current'->>'checked_at')::timestamptz >= (select oldest::timestamp at time zone 'UTC' from bounds)
        then t.old->'current'
      else jsonb_build_object('state', 'no-data', 'status', null, 'ms', null, 'checked_at', null) end,
    'uptime_90d', case when d.total > 0 then d.ok / d.total else null end,
    'p50_ms', case when not p_full and d.has_old_days then coalesce((t.old->>'p50_ms')::numeric, p.p50, f.p50)
      else coalesce(p.p50, f.p50) end,
    'p95_ms', case when p_full then p.p95 else coalesce((t.old->>'p95_ms')::numeric, p.p95) end,
    'days', coalesce(d.days, '[]'::jsonb)) as value
  from targets t left join day_lists d on d.id = t.id left join ok_percentiles p on p.id = t.id
    left join fallback f on f.id = t.id left join latest l on l.id = t.id
)
select jsonb_build_object('generated_at', to_char(p_now at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
  'window_days', 90, 'schema', 1, 'targets', coalesce(jsonb_agg(value order by ord), '[]'::jsonb)) from result;
$$;
revoke all on function public.build_status_projection(text, timestamptz, jsonb, boolean) from public, anon, authenticated;
grant execute on function public.build_status_projection(text, timestamptz, jsonb, boolean) to service_role;

create function public.rebuild_status_projection(p_runner text)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  v_state public.status_collector_leases%rowtype;
  v_now timestamptz;
  v_summary jsonb;
begin
  select * into v_state from public.status_collector_leases where runner = p_runner for update skip locked;
  if not found then
    if exists (select 1 from public.status_collector_leases where runner = p_runner) then return jsonb_build_object('state', 'busy'); end if;
    raise exception 'Collector runner is not configured';
  end if;
  if v_state.lease_expires_at > clock_timestamp() then return jsonb_build_object('state', 'busy'); end if;
  v_now := greatest(clock_timestamp(), coalesce((select generated_at from public.status_current where runner = p_runner), '-infinity'::timestamptz));
  v_summary := public.build_status_projection(p_runner, v_now, v_state.targets, true);
  insert into public.status_current (runner, generated_at, summary) values (p_runner, v_now, v_summary)
    on conflict (runner) do update set generated_at = excluded.generated_at, summary = excluded.summary;
  return jsonb_build_object('state', 'complete', 'generated_at', v_now);
end;
$$;
revoke all on function public.rebuild_status_projection(text) from public, anon, authenticated;
grant execute on function public.rebuild_status_projection(text) to service_role;
